python runnable.py SortingnConcat.scala  
python runnable.py RealTimeQueue.scala 
python runnable.py CyclicFibStream.scala   
python runnable.py PreciseBottomUpMegeSort.scala 
python runnable.py LazyNumericalRep.scala   
python runnable.py Deque.scala  
python runnable.py FibonacciMemoized.scala  
python runnable.py Knapsack.scala   
python runnable.py WeightedScheduling.scala 
python runnable.py LongestCommonSubsequence.scala   
python runnable.py LevenshteinDistance.scala 
python runnable.py PackratParsing.scala  
python runnable.py StreamLibrary.scala 
python runnable.py StreamClient.scala 
python runnable.py ConcTrees.scala 
python runnable.py Conqueue.scala 
python runnable.py CyclicHammingStream.scala   
python runnable.py BottomUpMegeSort.scala 	
python runnable.py HammingMemoized.scala    
python runnable.py NewViterbi.scala  
